name: CI Run Windows

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build && Test
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Invoke-Build
        run: |
          rustc --version
          rustup --version
          rustfmt --version
          cargo --version
          cargo clippy --version
          cargo audit --version
          pwsh --version
          Install-Module -Name invokebuild -Force -RequiredVersion 5.6.1
          Invoke-Build -Platform Windows64
