name: CI Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build && Test
    runs-on: ubuntu-20.04
    steps:
      - name: Invoke-Build
        uses: actions/checkout@v2
        run: |
          rustc --version
          rustup --version
          rustfmt --version
          cargo --version
          cargo clippy --version
          cargo audit --version
          pwsh --version
          Install-Module -Name invokebuild -Force -RequiredVersion 5.6.1
          Invoke-Build
